### Create get or create profile
GET http://localhost:4000/user/profile HTTP/1.1
content-type: application/json

### Not found page
GET http://localhost:4000/not-found HTTP/1.1
content-type: application/json

### Get settings
GET http://localhost:4000/user/settings HTTP/1.1
content-type: application/json

### Change team name with error
PUT http://localhost:4000/team/01FXTEJHRTDBSP49WGDZBH192Y/name HTTP/1.1
content-type: application/json

{
  "title": "new Hello world"
}

### Change team name
PUT http://localhost:4000/team/01FXTXQ28YV3B6EV55BQ51ESKG/name HTTP/1.1
content-type: application/json

{
  "displayName": "team one"
}

### Create Todo
# @name todoCreation
POST http://localhost:4000/01FXTXQ28YV3B6EV55BQ51ESKG/todo/create HTTP/1.1
content-type: application/json

{
  "title": "new Hello world"
}

### Create Todo with error, incorrect team ID
POST http://localhost:4000/01FX8KVHG514G6MZV87167G0Q02/todo/create HTTP/1.1
content-type: application/json

{
  "title": "new Hello world"
}

### Create Todo with error, `title` shouldn't be empty
POST http://localhost:4000/01FX8KVHG514G6MZV87167G0Q0/todo/create HTTP/1.1
content-type: application/json

{
  "title": ""
}

### Get Todo with invalid ID
GET http://localhost:4000/01FX8KVHG514G6MZV87167G0Q0/todo/123 HTTP/1.1

### Get Todo
@id = {{todoCreation.response.body.$.id}}
GET http://localhost:4000/01FX8KVHG514G6MZV87167G0Q0/todo/{{id}} HTTP/1.1

### Update Todo with invalid ID
PUT http://localhost:4000/01FX8KVHG514G6MZV87167G0Q0/todo/123 HTTP/1.1
content-type: application/json

{
  "title": "Hello world 1000"
}

### Update Todo
@id = {{todoCreation.response.body.$.id}}
PUT http://localhost:4000/01FX8KVHG514G6MZV87167G0Q0/todo/{{id}} HTTP/1.1
content-type: application/json

{
  "title": "Hello world 1000"
}

### Delete Todo with invalid ID
DELETE http://localhost:4000/01FX8KVHG514G6MZV87167G0Q0/todo/123 HTTP/1.1

### Delete Todo
@id = {{todoCreation.response.body.$.id}}
DELETE http://localhost:4000/01FX8KVHG514G6MZV87167G0Q0/todo/{{id}} HTTP/1.1

### List Todo
GET http://localhost:4000/01FX8KVHG514G6MZV87167G0Q0/todo/list HTTP/1.1

### Stripe create session
POST http://localhost:4000/billing/create-checkout-session HTTP/1.1
content-type: application/json

{
  "priceId": "price_1JSmUjGrcfaiexgslH41e88g"
}

### Stripe create session with invalid price
POST http://localhost:4000/billing/create-checkout-session HTTP/1.1
content-type: application/json

{
  "priceId": "price_1In575EK74ldPEzAusBLAt"
}

### Create Stripe customer portal link
POST http://localhost:4000/billing/customer-portal HTTP/1.1
content-type: application/json
