# You don't need to change the following `service` value for one project.
# But, when you have multiple projects, it'll have name collision.
# So, you can replace service name and use an alphanumeric name
# Please also update the name in https://github.com/Nextlessjs/nextless-infra/blob/main/sst.json
# Don't forget to append the '-infra' in the name in Nextless Infra
service: nextless

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, 'offline'}
  region: ${opt:region, 'us-east-1'}
  # Name of the SST app that's deploying our infrastructure
  sstApp: ${self:custom.stage}-${self:service}-infra
  tableName:
    offline: ${self:service}
    staging: !ImportValue '${self:custom.sstApp}-TableName'
    prod: !ImportValue '${self:custom.sstApp}-TableName'
  nodeEnv:
    offline: 'development'
    staging: 'production'
    prod: 'production'
  noAuth:
    offline: true
    staging: false
    prod: false

  bundle:
    linting: false
    excludeFiles: "**/*.test.ts"
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true
    noAuth: ${self:custom.noAuth.${self:custom.stage}}

provider:
  name: aws
  stage: ${self:custom.stage}
  runtime: nodejs14.x
  memorySize: 512
  timeout: 10
  logRetentionInDays: 90
  logs:
    httpApi: true
  httpApi:
    # metrics: true # Enable if you need
    cors:
      allowedOrigins:
        # In serverless 2, this step was automatically done but, serverless>=3.0.0 introduces changes that significantly impacts this step.
        # FIXME: Update the allowedOrigin to matched the environment variable `FRONTEND_DOMAIN_URL`.
        - http://localhost:3000
      allowedHeaders: # Set the default value from Serverless framework, this workaround is needed by serverless-offline
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
          # Restrict our IAM role permissions to
          # the specific table for the stage
          Resource:
            - !ImportValue '${self:custom.sstApp}-TableArn'
        - Effect: 'Allow'
          Action:
            - ses:SendRawEmail
          Resource: "*"

  environment:
    TABLE_NAME: ${self:custom.tableName.${self:custom.stage}}
    STAGE: ${self:custom.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_ENV: ${self:custom.nodeEnv.${self:custom.stage}}

functions:
  app:
    handler: src/handler.handler
    reservedConcurrency: 30
    events:
      - httpApi:
          path: '/billing/webhook'
          method: 'POST'

      - httpApi:
          path: '/{proxy+}'
          method: 'GET'
          authorizer:
            type: aws_iam

      - httpApi:
          path: '/{proxy+}'
          method: 'POST'
          authorizer:
            type: aws_iam

      - httpApi:
          path: '/{proxy+}'
          method: 'PUT'
          authorizer:
            type: aws_iam

      - httpApi:
          path: '/{proxy+}'
          method: 'DELETE'
          authorizer:
            type: aws_iam

resources:
  # Cognito Identity Pool Policy
  - ${file(./aws-resources/cognito-policy.yml)}
  - ${file(./aws-resources/dynamodb.${opt:stage, 'offline'}.yml), ''}

package:
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-bundle
  - '@nearst/serverless-dynalite'
  - serverless-offline-ses-v2
  - serverless-offline
