// You can add additional information related to your billing plan.
// In this example, we only use stripeProductId but, you can add more information if needed.
type IPricing = {
  id: string;
  name: string;
};

// Billing Plan for one environment
type IBillingPlanEnv = {
  [k: string]: {
    free: IPricing;
    [k: string]: IPricing;
  };
};

export const BillingPlan: IBillingPlanEnv = {
  dev: {
    free: {
      id: 'FREE',
      name: 'Free',
    },
    // FIXME: Add your `product id` for dev environment
    // The `product id` is generated by Stripe
    // Please check `Nextless-Quick-Start` repo on how to generate the `product id`
    prod_K70Vg9JW6WW97Q: {
      id: 'PRO',
      name: 'Pro',
    },
    // You can add more product id by following the same format
  },
  prod: {
    free: {
      id: 'FREE',
      name: 'Free',
    },
    // FIXME: Add your `product id` for prod environment
    // The `product id` is generated by Stripe
    // Please check `Nextless-Quick-Start` repo on how to generate the `product id`
  },
};
