// You can add additional information related to your billing plan.
// In this example, we only use stripeProductId but, you can add more information if needed.
type IPricing = {
  id: string;
  name: string;
};

export type IBillingPlanEnv = {
  free: IPricing;
  [k: string]: IPricing;
};

// Billing Plan for one environment
type IBillingPlan = {
  [k: string]: IBillingPlanEnv;
};

export const BillingPlan: IBillingPlan = {
  dev: {
    free: {
      id: 'FREE',
      name: 'Free',
    },
    // FIXME: Add your `product id` for dev environment
    // The `product id` is generated by Stripe
    // Please check `Nextless-Quick-Start` repo on how to generate the `product id`
    // Don't forget to also update the test which also use the `product id`
    prod_L9qynlbBRMmJi7: {
      id: 'PRO',
      name: 'Pro',
    },
    prod_L9qzBYonAfeceq: {
      id: 'ENTERPRISE',
      name: 'Enterprise',
    },
    // You can add more product id by following the same format
  },
  prod: {
    free: {
      id: 'FREE',
      name: 'Free',
    },
    // FIXME: Add your `product id` for prod environment
    // The `product id` is generated by Stripe
    // Please check `Nextless-Quick-Start` repo on how to generate the `product id`
  },
};
