name: CI for Backend with Docker

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Load Environment Variables from GitHub Secrets
        run: |
          {
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}"
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}"
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}"
            echo "DATABASE_URL=postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/${{ secrets.POSTGRES_DB }}"
          } > .env

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Docker Image
        run: docker build -t backend:test .

      - name: Run Docker Container
        run: |
          docker run -d --name backend_test_container -p 4000:4000 backend:test
          sleep 10
          docker logs backend_test_container

      - name: Check if Container is Running
        run: |
          if [ "$(docker inspect -f '{{.State.Running}}' backend_test_container)" != "true" ]; then
            echo "Container is not running"
            exit 1
          fi

      - name: Clean Up
        if: always()
        run: |
          docker stop backend_test_container || true
          docker rm backend_test_container || true
          docker rmi backend:test || true
